# Generated by Django 6.0.2 on 2026-03-01 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0009_productoglobal_productotienda_producto_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetidorScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Imprenta Okey, Gráfica VM, etc.', max_length=150, verbose_name='nombre del competidor')),
                ('url', models.URLField(help_text='Página exacta donde se encuentra el precio de este producto en la competencia.', verbose_name='URL a scrapear')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el bot debe visitar esta URL o si está pausada.', verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('producto', models.ForeignKey(help_text='Producto propio al que se le buscarán precios competidores.', on_delete=django.db.models.deletion.CASCADE, related_name='competidores_scraping', to='tenant_app.productotienda', verbose_name='producto objetivo')),
            ],
            options={
                'verbose_name': 'competidor para scraping',
                'verbose_name_plural': 'competidores para scraping',
                'ordering': ['producto', 'nombre'],
            },
        ),
    ]
