# Generated by Django 6.0.2 on 2026-03-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0010_competidorscraping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotienda',
            name='nombre',
            field=models.CharField(default='Producto Nuevo', help_text='Nombre de venta del producto (ej: Tarjetas de presentación 300g).', max_length=150, verbose_name='nombre del producto'),
        ),
    ]
