# Generated by Django 6.0.2 on 2026-03-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0011_productotienda_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productotienda',
            options={'ordering': ['orden_visual', '-creado_en'], 'verbose_name': 'producto de tienda', 'verbose_name_plural': 'productos de tienda'},
        ),
        migrations.AddField(
            model_name='productotienda',
            name='orden_visual',
            field=models.IntegerField(default=0, help_text='Define la posición manual del producto en la tienda (Drag & Drop).', verbose_name='orden en catálogo'),
        ),
    ]
