# Generated by Django 6.0.2 on 2026-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0012_alter_productotienda_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialScraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha de ejecución')),
                ('producto_scrapeado', models.CharField(max_length=255, verbose_name='producto scrapeado')),
                ('estado', models.CharField(choices=[('EXITO', 'Éxito'), ('ADVERTENCIA', 'Éxito parcial / Advertencias'), ('ERROR', 'Error')], default='EXITO', max_length=50, verbose_name='estado final')),
                ('detalles', models.TextField(blank=True, verbose_name='detalles de la ejecución')),
            ],
            options={
                'verbose_name': 'historial de scraping',
                'verbose_name_plural': 'historial de scrapings',
                'ordering': ['-fecha'],
            },
        ),
    ]
