# Generated by Django 6.0.2 on 2026-03-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0013_historialscraping'),
    ]

    operations = [
        migrations.AddField(
            model_name='competidorscraping',
            name='email_detectado',
            field=models.EmailField(blank=True, help_text='Correo electrónico extraído automáticamente por el bot.', max_length=254, null=True, verbose_name='Email detectado'),
        ),
        migrations.AddField(
            model_name='competidorscraping',
            name='whatsapp_detectado',
            field=models.CharField(blank=True, help_text='Número extraído automáticamente por el bot. (Ej: +569...)', max_length=50, null=True, verbose_name='WhatsApp detectado'),
        ),
    ]
