# Generated by Django 6.0.2 on 2026-03-01 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0014_competidorscraping_email_detectado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre genérico de la empresa (Ej: Imprenta Okey).', max_length=150, unique=True, verbose_name='nombre del competidor')),
                ('sitio_web', models.URLField(blank=True, help_text='URL general de la imprenta.', null=True, verbose_name='sitio web principal')),
                ('whatsapp_detectado', models.CharField(blank=True, help_text='Número extraído automáticamente.', max_length=50, null=True, verbose_name='WhatsApp detectado')),
                ('email_detectado', models.EmailField(blank=True, help_text='Correo electrónico extraído automáticamente.', max_length=254, null=True, verbose_name='Email detectado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
            ],
            options={
                'verbose_name': 'proveedor competencia',
                'verbose_name_plural': 'proveedores competencia',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='competidorscraping',
            name='email_detectado',
            field=models.EmailField(blank=True, help_text='Correo electrónico extraído automáticamente por el bot.', max_length=254, null=True, verbose_name='Email detectado (obsoleto)'),
        ),
        migrations.AlterField(
            model_name='competidorscraping',
            name='nombre',
            field=models.CharField(help_text='Ej: Imprenta Okey, Gráfica VM, etc.', max_length=150, verbose_name='nombre del competidor (obsoleto)'),
        ),
        migrations.AlterField(
            model_name='competidorscraping',
            name='whatsapp_detectado',
            field=models.CharField(blank=True, help_text='Número extraído automáticamente por el bot. (Ej: +569...)', max_length=50, null=True, verbose_name='WhatsApp detectado (obsoleto)'),
        ),
        migrations.AddField(
            model_name='competidorscraping',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrapings', to='tenant_app.proveedorcompetencia', verbose_name='Proveedor competidor'),
        ),
    ]
