# Generated by Django 6.0.2 on 2026-03-01 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0016_auto_20260301_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competidorscraping',
            options={'ordering': ['producto', 'proveedor__nombre'], 'verbose_name': 'competidor para scraping', 'verbose_name_plural': 'competidores para scraping'},
        ),
        migrations.RemoveField(
            model_name='competidorscraping',
            name='email_detectado',
        ),
        migrations.RemoveField(
            model_name='competidorscraping',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='competidorscraping',
            name='whatsapp_detectado',
        ),
        migrations.AlterField(
            model_name='competidorscraping',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapings', to='tenant_app.proveedorcompetencia', verbose_name='Proveedor competidor'),
        ),
    ]
