# Generated by Django 6.0.2 on 2026-03-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0017_alter_competidorscraping_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competidorscraping',
            unique_together={('producto', 'proveedor')},
        ),
        migrations.AlterField(
            model_name='competidorscraping',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el bot debe visitar la URL de este proveedor o si está pausado.', verbose_name='activo'),
        ),
        migrations.RemoveField(
            model_name='competidorscraping',
            name='url',
        ),
    ]
