# Generated by Django 6.0.2 on 2026-03-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0018_alter_competidorscraping_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotienda',
            name='termino_busqueda',
            field=models.CharField(blank=True, help_text='Palabras clave que el bot usará para buscar este producto en la competencia. Si está vacío, se usa el nombre del producto. Ej: "pendón roller 80x200 cm doble cara"', max_length=200, null=True, verbose_name='término de búsqueda para scraping'),
        ),
        migrations.AddField(
            model_name='proveedorcompetencia',
            name='url_patron_busqueda',
            field=models.CharField(blank=True, help_text='Patrón personalizado con {q} como marcador para el término. Ej: "?s={q}" o "/search?query={q}". Si está vacío, el bot intentará patrones comúnes automáticamente.', max_length=300, null=True, verbose_name='patrón de URL del buscador'),
        ),
        migrations.AlterField(
            model_name='proveedorcompetencia',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='URL general de la imprenta. El bot navegará desde aquí.', null=True, verbose_name='sitio web principal'),
        ),
    ]
