# Generated by Django 5.1.6 on 2026-03-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0019_productotienda_termino_busqueda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productotienda',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen para mostrar en el catálogo de la tienda.', null=True, upload_to='productos/', verbose_name='imagen de vista previa'),
        ),
    ]
