# Generated by Django 5.1.6 on 2026-03-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0020_productotienda_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección física para retiro de pedidos.', max_length=255, null=True, verbose_name='dirección'),
        ),
    ]
