# Generated by Django 6.0.3 on 2026-03-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0021_tienda_direccion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competidorscraping',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='competidorscraping',
            constraint=models.UniqueConstraint(fields=('producto', 'proveedor'), name='unique_producto_proveedor'),
        ),
        migrations.AddConstraint(
            model_name='productotienda',
            constraint=models.CheckConstraint(condition=models.Q(('precio_base__gte', 0)), name='precio_base_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='productotienda',
            constraint=models.CheckConstraint(condition=models.Q(('margen_ganancia__gte', 0)), name='margen_ganancia_no_negativo'),
        ),
    ]
