# Generated by Django 6.0.3 on 2026-03-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0022_alter_competidorscraping_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Descripción que aparece bajo el título en los resultados de búsqueda. Máximo 160 caracteres.', max_length=160, null=True, verbose_name='descripción SEO'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Título que aparece en los resultados de búsqueda de Google. Máximo 70 caracteres. Si está vacío se usa el nombre de la tienda.', max_length=70, null=True, verbose_name='título SEO'),
        ),
    ]
