# Generated by Django 6.0.3 on 2026-03-08 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0023_tienda_seo_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, help_text='Número de contacto del comprador.', max_length=20, verbose_name='teléfono')),
                ('direccion_envio', models.CharField(blank=True, help_text='Dirección predeterminada para despachos.', max_length=255, verbose_name='dirección de envío')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('usuario', models.OneToOneField(help_text='Cuenta de acceso asociada a este comprador.', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'cliente final',
                'verbose_name_plural': 'clientes finales',
            },
        ),
        migrations.AddField(
            model_name='orden',
            name='comprador',
            field=models.ForeignKey(blank=True, help_text='Cliente final que realizó la compra. Nulo si fue un pago sin cuenta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='tenant_app.clientefinal', verbose_name='comprador'),
        ),
        migrations.AddIndex(
            model_name='orden',
            index=models.Index(fields=['comprador'], name='tenant_app__comprad_69b079_idx'),
        ),
    ]
