# Generated by Django 6.0.3 on 2026-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0024_clientefinal_orden_comprador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='plantilla_diseno',
            field=models.CharField(choices=[('minimalista', 'Minimalista'), ('moderno_oscuro', 'Moderno Oscuro'), ('creativo', 'Creativo')], default='minimalista', help_text='Tema visual para la tienda pública del subcontratista. Cada plantilla define el esquema de colores y estilo general.', max_length=20, verbose_name='plantilla de diseño'),
        ),
    ]
