# Generated by Django 6.0.3 on 2026-03-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_app', '0025_add_plantilla_diseno_to_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='color_primario',
            field=models.CharField(default='#2563EB', help_text='Color principal de la tienda en formato HEX (ej: #2563EB). Se usa en botones, acentos y el hero de la tienda pública.', max_length=7, verbose_name='color primario de marca'),
        ),
        migrations.AddField(
            model_name='tienda',
            name='color_secundario',
            field=models.CharField(default='#4f46e5', help_text='Color de apoyo en formato HEX (ej: #4f46e5). Se usa en degradados y elementos de hover.', max_length=7, verbose_name='color secundario de marca'),
        ),
    ]
